#!/bin/bash
# generate-config.sh — Generates config.js from a .env file
#
# Usage:
#   cp .env.example .env    # create your .env and fill in values
#   ./generate-config.sh    # generates config.js
#
# config.js is gitignored and safe to populate with real keys.

set -e

ENV_FILE=".env"
OUTPUT="config.js"

if [ ! -f "$ENV_FILE" ]; then
  echo "Error: $ENV_FILE not found."
  echo "Run: cp .env.example .env  and fill in your values."
  exit 1
fi

# Load .env (skip comments and blank lines)
export $(grep -v '^#' "$ENV_FILE" | grep -v '^$' | xargs)

# Validate required keys
REQUIRED=("ANAM_API_KEY" "ANAM_AVATAR_ID" "ANAM_VOICE_ID" "ANTHROPIC_API_KEY")
MISSING=()
for key in "${REQUIRED[@]}"; do
  if [ -z "${!key}" ]; then
    MISSING+=("$key")
  fi
done

if [ ${#MISSING[@]} -ne 0 ]; then
  echo "Error: Missing required variables in $ENV_FILE:"
  for m in "${MISSING[@]}"; do echo "  - $m"; done
  exit 1
fi

cat > "$OUTPUT" << EOF
// AUTO-GENERATED by generate-config.sh — do not edit manually
// Re-run ./generate-config.sh after changing .env
// This file is gitignored.

const CONFIG = {
  ANAM_API_KEY: '${ANAM_API_KEY}',
  ANAM_AVATAR_ID: '${ANAM_AVATAR_ID}',
  ANAM_VOICE_ID: '${ANAM_VOICE_ID}',

  ANTHROPIC_API_KEY: '${ANTHROPIC_API_KEY}',
  ANTHROPIC_MODEL: 'claude-sonnet-4-6',

  DEBOUNCE_MS: 1500,
  MAX_SPEECH_LENGTH: 500,
  MAX_CONVERSATION_HISTORY: 20
};
EOF

echo "Generated $OUTPUT from $ENV_FILE"
